### PR TITLE
Yandex Music Updates

### PR DESCRIPTION
**Pull request by Krispeckt**
* The recommendation logic for the track is implemented
* Added query argument to get full tracks without pain and checks
* Fixed parseCoverUri
* Wrote load limits for playlists, artists, albums

### CODE REVIEW

**Review by topi314 — CHANGES_REQUESTED** [review]
I am gonna assume you tested this

can you rebase these change onto master and add default config values like I did in my last commit?

also when you pass in a yandex .kz/.by should those links returned have that domain ending?

you should also add `ymrec:` to the readme

**Comment by Krispeckt** [comment]
> I am gonna assume you tested this
> 
> 
> 
> can you rebase these change onto master and add default config values like I did in my last commit?
> 
> 
> 
> also when you pass in a yandex .kz/.by should those links returned have that domain ending?
> 
> 
> 
> you should also add `ymrec:` to the readme

Yes, it's all been tested. Personally I had no problems, I'm not sure about deviant tracks, but if you refer to the json response from AgutinVBoy, such tracks really do not have the "available" key. About domains, they do exist (#164)[https://github.com/topi314/LavaSrc/issues/164] .

I will make a commit in the near future.

**Comment by topi314** [comment]
Yeah I saw you added those other domains to the regex which is fine

But all returned track links default to the standard domain atm, and I was asking if you want/should keep those domains when loading a track/playlist

**Comment by Krispeckt** [comment]
> Yeah I saw you added those other domains to the regex which is fine
> 
> But all returned track links default to the standard domain atm, and I was asking if you want/should keep those domains when loading a track/playlist 

I didn't understand the question from the beginning, sorry. Is that what you meant?

**Comment by Krispeckt** [comment]
:<

**Comment by topi314** [comment]
that was a terrible pr name lol

**Review by topi314 — APPROVED** [review]

**Comment by Krispeckt** [comment]
> anyway thanks for all the stuff

Lul, it's in my best interest too, since I use the plugin too

**Comment by topi314** [comment]
not even allowed to thank people anymore :(

**Pull request merged**
